### PR TITLE
Added a machine translation model

### PR DESCRIPTION
**Pull request by pandeyanuradha**
Added a Jupyter notebook that consists of the code for translating a corpus from the Hindi language to English.

### CODE REVIEW

**Comment by abhinand5** [comment]
It would be great if you can make the notebook a little more descriptive

**Comment by pandeyanuradha** [comment]
> It would be great if you can make the notebook a little more descriptive

Sure, I will make the changes.

**Comment by abhinand5** [comment]
Have you made the changes?

**Comment by abhinand5** [comment]
I am closing this PR because of lack of response.

**Pull request closed without merging**
